"""empty message

Revision ID: 1ddaae808dd0
Revises: 9cb2905c59ee
Create Date: 2025-11-07 16:08:23.805151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddaae808dd0'
down_revision = '9cb2905c59ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), server_default='uvl', nullable=False))
        batch_op.add_column(sa.Column('rows_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('schema_json', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_data_set_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_set_type'))
        batch_op.drop_column('schema_json')
        batch_op.drop_column('rows_count')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
