"""Initial migration

Revision ID: 9a04c4467877
Revises: 
Create Date: 2025-11-10 13:29:43.770218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a04c4467877'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorscommunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('banner_color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('community_curators',
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('community_id', 'user_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REMOVED', name='communitydatasetstatus'), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabular_meta_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hubfile_id', sa.Integer(), nullable=True),
    sa.Column('delimiter', sa.String(length=5), nullable=True),
    sa.Column('encoding', sa.String(length=20), nullable=True),
    sa.Column('has_header', sa.Boolean(), nullable=True),
    sa.Column('n_rows', sa.Integer(), nullable=True),
    sa.Column('n_cols', sa.Integer(), nullable=True),
    sa.Column('primary_keys', sa.JSON(), nullable=True),
    sa.Column('index_cols', sa.JSON(), nullable=True),
    sa.Column('sample_rows', sa.JSON(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id')
    )
    op.create_table('tabular_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('null_ratio', sa.Float(), nullable=True),
    sa.Column('avg_cardinality', sa.Float(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id')
    )
    op.create_table('tabular_column',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dtype', sa.String(length=50), nullable=True),
    sa.Column('null_count', sa.Integer(), nullable=True),
    sa.Column('unique_count', sa.Integer(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['tabular_meta_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notepad')
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), server_default='uvl', nullable=False))
        batch_op.add_column(sa.Column('rows_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('schema_json', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_data_set_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_set_type'))
        batch_op.drop_column('schema_json')
        batch_op.drop_column('rows_count')
        batch_op.drop_column('type')

    op.create_table('notepad',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('notepad_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tabular_column')
    op.drop_table('tabular_metrics')
    op.drop_table('tabular_meta_data')
    op.drop_table('community_dataset')
    op.drop_table('comments')
    op.drop_table('community_curators')
    op.drop_table('community')
    op.drop_table('authorscommunities')
    # ### end Alembic commands ###
