"""empty message

Revision ID: ab77c3339f69
Revises: 1ddaae808dd0
Create Date: 2025-11-07 21:27:38.935437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab77c3339f69'
down_revision = '1ddaae808dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('schema_json')
        batch_op.drop_column('rows_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rows_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('schema_json', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
