name: Comprobar vulnerabilidades de dependencias

on: 
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar safety
        run: pip install safety

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Escanear vulnerabilidades
        run: safety check -r requirements.txt
