name: Añadir cabecera LGPL v3 automáticamente

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  add-lgpl-header:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Añadir cabecera LGPL v3 a scripts Python modificados
        env:
          GIT_AUTHOR: ${{ github.actor }}
        run: |
          LICENSE_HEADER='""" 
          Copyright (C) 2025 Mi Empresa

          Este archivo forma parte de rubikhub.

          rubikhub es software libre: puede redistribuirlo y/o modificarlo
          bajo los términos de la GNU Lesser General Public License publicada por la
          Free Software Foundation, ya sea la versión 3 de la Licencia, o (a su elección)
          cualquier versión posterior.

          """'

          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.py')

          if [ -z "$FILES" ]; then
            echo "No hay archivos Python modificados."
            exit 0
          fi

          for FILE in $FILES; do
            if [ -f "$FILE" ]; then
              if ! grep -qi "LGPL" "$FILE"; then
                echo "Añadiendo cabecera LGPL v3 a $FILE"
                sed -i "1i$LICENSE_HEADER\n" "$FILE"
              else
                echo "Cabecera ya presente en $FILE, no se modifica."
              fi
            fi
          done

      - name: Confirmar y subir cambios si hay modificaciones
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Añadir cabecera LGPL v3 automáticamente"
            git push
          else
            echo "No hay cambios que subir"
          fi
