name: Security Checks

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  security:
    name: Security checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Audit dependencies
        run: pip audit --all --fail-on=moderate

      - name: Check for secrets
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog
          trufflehog --version || true
          trufflehog --help || true
          trufflehog filesystem --directory . --json || true